//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayOfTheWeek.ConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDayOfTheWeekService")]
    public interface IDayOfTheWeekService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfTheWeekService/GetDayOfTheWeek", ReplyAction="http://tempuri.org/IDayOfTheWeekService/GetDayOfTheWeekResponse")]
        string GetDayOfTheWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDayOfTheWeekService/GetDayOfTheWeek", ReplyAction="http://tempuri.org/IDayOfTheWeekService/GetDayOfTheWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOfTheWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDayOfTheWeekServiceChannel : DayOfTheWeek.ConsoleClient.ServiceReference1.IDayOfTheWeekService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DayOfTheWeekServiceClient : System.ServiceModel.ClientBase<DayOfTheWeek.ConsoleClient.ServiceReference1.IDayOfTheWeekService>, DayOfTheWeek.ConsoleClient.ServiceReference1.IDayOfTheWeekService {
        
        public DayOfTheWeekServiceClient() {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfTheWeekServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DayOfTheWeekServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfTheWeek(System.DateTime date) {
            return base.Channel.GetDayOfTheWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfTheWeekAsync(System.DateTime date) {
            return base.Channel.GetDayOfTheWeekAsync(date);
        }
    }
}
